#define NV_IS_EXPORT_SYMBOL_GPL_of_node_to_nid 0
#define NV_IS_EXPORT_SYMBOL_GPL_sme_active 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_swiotlb_map_sg_attrs 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_swiotlb_dma_ops 0
#define NV_IS_EXPORT_SYMBOL_PRESENT___close_fd 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_close_fd 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_get_unused_fd 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_get_unused_fd_flags 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_nvhost_get_default_device 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_nvhost_syncpt_unit_interface_get_byte_offset 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_nvhost_syncpt_unit_interface_get_aperture 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_dce_register_ipc_client 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_dce_unregister_ipc_client 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_dce_client_ipc_send_recv 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_dram_clk_to_mc_clk 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_get_dram_num_channels 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_dram_types 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_pxm_to_node 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_screen_info 1
#define NV_IS_EXPORT_SYMBOL_GPL_screen_info 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_i2c_bus_status 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_fuse_control_read 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_get_platform 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_pci_find_host_bridge 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_send_cmd 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_set_init_cb 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_clear_init_cb 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_alloc_mem_from_gscco 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_free_gscco_mem 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_memory_block_size_bytes 1
#define NV_CRYPTO_PRESENT
#undef NV_CRYPTO_AKCIPHER_VERIFY_PRESENT
#define NV_IS_EXPORT_SYMBOL_PRESENT_follow_pte 0
#undef NV_FOLLOW_PTE_ARG1_VMA
#define NV_IS_EXPORT_SYMBOL_PRESENT_follow_pfnmap_start 1
#define NV_IS_EXPORT_SYMBOL_GPL_pci_ats_supported 1
#undef NV_ECC_DIGITS_FROM_BYTES_PRESENT
#define NV_IS_EXPORT_SYMBOL_GPL_set_memory_encrypted 1
#define NV_IS_EXPORT_SYMBOL_GPL_set_memory_decrypted 1
#define NV_IS_EXPORT_SYMBOL_GPL___platform_driver_register 1
#define NV_IS_EXPORT_SYMBOL_PRESENT___platform_driver_register 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_hrtimer_setup 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_timer_delete_sync 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_int_active_memcg 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_migrate_vma_setup 1
#define NV_IS_EXPORT_SYMBOL_PRESENT___iowrite64_lo_hi 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_make_device_exclusive 0
// Kernel version:             "6.13.12-061312-generic"
